### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by MonoS** [Irrational-Encoding-Wizardry/vs-tools#3]
When importing lvsfunc or vsaa i get error
`AttributeError: 'NoneType' object has no attribute 'isatty'`

The full traceback
```
Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate
File "F:\test.vpy", line 6, in import lvsfunc
File "C:\Program Files\Python310\lib\site-packages\lvsfunc\__init__.py", line 12, in 
from . import (aa, comparison, deblock, dehalo, dehardsub, deinterlace, exceptions, fun, helpers, mask, misc, noise,
File "C:\Program Files\Python310\lib\site-packages\lvsfunc\aa.py", line 7, in 
from vskernels import Bicubic, Box, Catrom, Point
File "C:\Program Files\Python310\lib\site-packages\vskernels\__init__.py", line 15, in 
from . import exceptions, kernels, util
File "C:\Program Files\Python310\lib\site-packages\vskernels\exceptions.py", line 5, in 
from vstools import CustomValueError, FuncExceptT
File "C:\Program Files\Python310\lib\site-packages\vstools\__init__.py", line 1, in 
from .enums import * # noqa: F401, F403
File "C:\Program Files\Python310\lib\site-packages\vstools\enums\__init__.py", line 1, in 
from .base import * # noqa: F401, F403
File "C:\Program Files\Python310\lib\site-packages\vstools\enums\base.py", line 6, in 
from ..exceptions import NotFoundEnumValue
File "C:\Program Files\Python310\lib\site-packages\vstools\exceptions\__init__.py", line 1, in 
from .base import * # noqa: F401, F403
File "C:\Program Files\Python310\lib\site-packages\vstools\exceptions\base.py", line 40, in 
class CustomError(Exception, metaclass=CustomErrorMeta):
File "C:\Program Files\Python310\lib\site-packages\vstools\exceptions\base.py", line 32, in __new__
if sys.stdout.isatty():
AttributeError: 'NoneType' object has no attribute 'isatty'
```

I've updated lvsfunc, vsaa and vstools from git passing the --upgrade flag to pip.

**Comment by Setsugennoao** [comment]
Thanks for the error report.

Apparently `stdout` can sometimes not be connected, and it'll result in it being `None`.
Even `print` internally has a check for it.
https://github.com/python/cpython/blob/3.11/Python/bltinmodule.c#L2000-L2003

Fixed it in https://github.com/Irrational-Encoding-Wizardry/vs-tools/commit/adaa2fddf549d70a853fe14e21296aec72814072
